### ISSUE TITLE
submodule using https:// instead of git@

### ISSUE THREAD

**Issue by house-mouse** [carlk3/FreeRTOS-FAT-CLI-for-RPi-Pico#6]
Hello and thank you for this super awesome project!

It would be super helpful if you could change the gitmodule reference that you use from 
-       url = git@github.com:FreeRTOS/FreeRTOS-Kernel.git
to
+       url = https://github.com/FreeRTOS/FreeRTOS-Kernel.git

the https version is anonymous.  The git version causes a variety of my projects to stumble on credentials which is ... unfortunate.

Thanks again!

**Comment by carlk3** [comment]
Hello house-mouse,

Please review Pull Request #9
